// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-u6C4ZcWQ8TQaFEZNX5iKuX-0QA92IwM',
    appId: '1:542286750516:web:ff6b0ea1913b680ba2fb61',
    messagingSenderId: '542286750516',
    projectId: 'hossy-barbers',
    authDomain: 'hossy-barbers.firebaseapp.com',
    storageBucket: 'hossy-barbers.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo553EPQYzG2gMbwR1lk_QwGSV5gyvVyY',
    appId: '1:542286750516:android:e1589b2df5efdedea2fb61',
    messagingSenderId: '542286750516',
    projectId: 'hossy-barbers',
    storageBucket: 'hossy-barbers.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcJD9-VOhYSVeUWtn_6Zi-JdzzaOGIhmc',
    appId: '1:542286750516:ios:2403ef6be0bbe1eaa2fb61',
    messagingSenderId: '542286750516',
    projectId: 'hossy-barbers',
    storageBucket: 'hossy-barbers.firebasestorage.app',
    iosBundleId: 'com.example.hossyBarbers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcJD9-VOhYSVeUWtn_6Zi-JdzzaOGIhmc',
    appId: '1:542286750516:ios:2403ef6be0bbe1eaa2fb61',
    messagingSenderId: '542286750516',
    projectId: 'hossy-barbers',
    storageBucket: 'hossy-barbers.firebasestorage.app',
    iosBundleId: 'com.example.hossyBarbers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-u6C4ZcWQ8TQaFEZNX5iKuX-0QA92IwM',
    appId: '1:542286750516:web:959a20d1cc545c16a2fb61',
    messagingSenderId: '542286750516',
    projectId: 'hossy-barbers',
    authDomain: 'hossy-barbers.firebaseapp.com',
    storageBucket: 'hossy-barbers.firebasestorage.app',
  );
}
